-- ZCredit by Money Life — Supabase schema
-- Run this in Supabase SQL Editor.
-- This is designed for the fictional Money Life economy.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  cardholder_name text not null default 'YOUR NAME',
  card_number text unique,
  expiry text default '09/30',
  balance numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('deposit','transfer')),
  title text not null,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.deposit_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','completed')),
  created_at timestamptz not null default now()
);

create table if not exists public.transfer_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','completed')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.transactions enable row level security;
alter table public.deposit_requests enable row level security;
alter table public.transfer_requests enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated using (id = auth.uid() or true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert to authenticated with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own" on public.transactions
for select to authenticated using (user_id = auth.uid());

drop policy if exists "deposit_requests_own" on public.deposit_requests;
create policy "deposit_requests_own" on public.deposit_requests
for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "transfer_requests_sender" on public.transfer_requests;
create policy "transfer_requests_sender" on public.transfer_requests
for insert to authenticated with check (sender_id = auth.uid());

drop policy if exists "transfer_requests_select" on public.transfer_requests;
create policy "transfer_requests_select" on public.transfer_requests
for select to authenticated using (sender_id = auth.uid() or recipient_id = auth.uid());

-- IMPORTANT:
-- Admin balance changes should be performed by a secure server/admin function
-- using the Supabase service role key. NEVER put the service-role key in this HTML app.
